# ensembles
## supervised
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_supervised_best/ --predictions_prefix 2nd_ep

## dino
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_dino/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_dino_best/ --predictions_prefix 2nd_

## supervised comparable
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_supervised_comparable_01/ --predictions_prefix 2nd_ep --target_mse 0.0922 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_supervised_comparable_03/ --predictions_prefix 2nd_ep --target_mse 0.0946 --ensemble_size 3
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_supervised_comparable_05/ --predictions_prefix 2nd_ep --target_mse 0.0953 --ensemble_size 5
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_supervised_comparable_10/ --predictions_prefix 2nd_ep --target_mse 0.0987 --ensemble_size 10
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/ensembles/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/ensembles/outputs_supervised_comparable_20/ --predictions_prefix 2nd_ep --target_mse 0.103 --ensemble_size 20

# aleatoric ensemble
## supervised
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_supervised_best/ --predictions_prefix 2nd_ep

## dino
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_dino/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_dino_best/ --predictions_prefix 2nd_ep

## supervised comparable
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_supervised_comparable_01/ --predictions_prefix 2nd_ep --target_mse 0.0974 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_supervised_comparable_03/ --predictions_prefix 2nd_ep --target_mse 0.0975 --ensemble_size 3
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_supervised_comparable_05/ --predictions_prefix 2nd_ep --target_mse 0.0975 --ensemble_size 5
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_supervised_comparable_10/ --predictions_prefix 2nd_ep --target_mse 0.0985 --ensemble_size 10
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric_ensemble/output_aleatoric_supervised_comparable_20/ --predictions_prefix 2nd_ep --target_mse 0.11 --ensemble_size 20

# aleatoric
## supervised
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/model_supervised_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_best_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/model_supervised_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_best_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/model_supervised_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_best_3/ --predictions_prefix 2nd_ep
## supervised whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done
## dino
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/model_dino_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_dino_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/model_dino_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_dino_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/model_dino_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_dino_3/ --predictions_prefix 2nd_ep
## dino whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_dino/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_dino_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done
## comparable
### hand selected values around the dino mse values. For the real values it resulted in the same checkpoint for every run
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_comparable_1/ --predictions_prefix 2nd_ep --target_mse 0.09735 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_comparable_2/ --predictions_prefix 2nd_ep --target_mse 0.0958 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/aleatoric/models_supervised/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/aleatoric/aleatoric/outputs_supervised_comparable_3/ --predictions_prefix 2nd_ep --target_mse 0.0983 --ensemble_size 1


#mcbn
## supervised
### manual tsp
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_1/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); echo PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_1/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_2/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); echo PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_2/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_3/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); echo PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_3/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
# more samples for comparable
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_4/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_4/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_5/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_5/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_6/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_6/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_7/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_7/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_8/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_8/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_9/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_9/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
for d in /home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_10/*/checkpoint_supervised_resnet18_RegressionHead_ep*; do e=$(grep -Po "(?<=ep)[0-9]{4}" <<< $d); PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "$d" --pretrained_weights_head "$d" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --name "ep$e" --output_base_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_10/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv; done
# wo uct
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --pretrained_weights_backbone "/home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_1/2022_12_6__02_32_15___ezaob/checkpoint_best_supervised_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_1/2022_12_6__02_32_15___ezaob/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_without_uct/1/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --pretrained_weights_backbone "/home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_2/2022_12_6__04_46_04___mxxbm/checkpoint_best_supervised_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_2/2022_12_6__04_46_04___mxxbm/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_without_uct/2/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --pretrained_weights_backbone "/home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_3/2022_12_6__03_48_55___zxwhz/checkpoint_best_supervised_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_supervised_best_3/2022_12_6__03_48_55___zxwhz/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_supervised_best_without_uct/3/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32


# MANUAL STEP!!
# for supervised
# copy together to mcbn/3_mcbn_model_supervised_with_std_best_x/model/
# - from 1_model_supervised_best_x: log.txt, checkpoint_best_supervised_resnet18.txt, config.json
# - from 2_output_mcbn_model_supervised_best_x: *_predictions.csv*
# for comparable supervised
# - copy together the models folders of previous supervised step into 3_models_supervised_with_std as model1, model2, model3
# for dino: nothin, simplified wihtout training progress stats

PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_mcbn_model_supervised_with_std_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_final_supervised_best_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_mcbn_model_supervised_with_std_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_final_supervised_best_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_mcbn_model_supervised_with_std_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_final_supervised_best_3/ --predictions_prefix 2nd_ep
## supervised whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_models_supervised_with_std/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_outputs_supervised_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done

## dino
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__21_04_09___tvdye/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_1/2022_11_6__01_57_39___eadxv/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_1/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__16_54_26___yslcr/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_2/2022_12_5__23_05_47___suqcl/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_2/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_11_1__05_11_00___vqzkh/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_3/2022_11_6__02_34_45___zbkze/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_3/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_11_2__01_07_12___rngqx/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_4/2022_12_6__01_14_35___gluim/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_4/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_11_2__01_07_25___zetoq/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_5/2022_12_6__01_41_22___zkkhi/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_5/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_11_1__23_34_31___jyfmi/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_6/2022_12_6__00_23_45___kmxse/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_6/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__20_11_05___wnuih/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_7/2022_12_6__00_07_27___qpqpr/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_7/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_11_2__01_27_06___dusub/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_8/2022_12_6__02_13_10___qegne/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_8/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__21_02_02___ygqma/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_9/2022_11_6__02_14_31___cqlyx/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_9/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --uncertainty_type mcbn --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__20_48_29___txqbw/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_10/2022_12_6__00_41_20___ckvyl/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --show_predictions 0 --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_10/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32 --mcbn_batchsize 128 --uncertainty_iters 64 --csv_name train_chapters.csv
# wo uct
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__21_04_09___tvdye/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_1/2022_11_6__01_57_39___eadxv/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_without_uct/1/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_10_6__16_54_26___yslcr/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_2/2022_12_5__23_05_47___suqcl/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_without_uct/2/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32
PYTHONPATH=./ WANDB_MODE=offline tsp python main.py --mode test --pretrained_weights_backbone "/home/markus/workspace/data/final_data/ensembles/models_dino/2022_11_1__05_11_00___vqzkh/checkpoint_best_dino_resnet18.pth" --pretrained_weights_head "/home/markus/workspace/data/final_data/mcbn/1_model_dino_best_3/2022_11_6__02_34_45___zbkze/checkpoint_best_supervised_resnet18.pth" --arch resnet18 --batch_size 128 --csv_name_test validation_chapters_1_2.csv --csv_name_test2 test_chapters.csv --override_output_dir /home/markus/workspace/data/final_data/mcbn/2_output_mcbn_model_dino_best_without_uct/3/ --data_path /home/markus/datasets/drive360_prepared_5_5k/ --net_resolution 224 224 --num_workers 32

## comparable
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_models_supervised_with_std/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_final_supervised_comparable_1/ --predictions_prefix 2nd_ep --target_mse 0.0155 --ensemble_size 1  # custom value because it resulted in the same as 0.0160
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_models_supervised_with_std/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_final_supervised_comparable_2/ --predictions_prefix 2nd_ep --target_mse 0.0160 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/mcbn/3_models_supervised_with_std/ --dataset_dir /home/markus/datasets/drive360_prepared_5_5k/ --output_dir /home/markus/workspace/data/final_data/mcbn/4_final_supervised_comparable_3/ --predictions_prefix 2nd_ep --target_mse 0.0167 --ensemble_size 1


# ---removed---
# bbb - paper_proposal_all_epochs
## supervised
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_supervised_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_supervised_best_1/ --predictions_prefix 2nd_ep
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_supervised_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_supervised_best_2/ --predictions_prefix 2nd_ep
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_supervised_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_supervised_best_3/ --predictions_prefix 2nd_ep

## dino
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_dino_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_dino_best_1/ --predictions_prefix 2nd_ep
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_dino_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_dino_best_2/ --predictions_prefix 2nd_ep
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_dino_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_dino_best_3/ --predictions_prefix 2nd_ep

## comparable
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_supervised_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_supervised_comparable_1/ --predictions_prefix 2nd_ep --target_mse 0.0988
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_supervised_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_supervised_comparable_2/ --predictions_prefix 2nd_ep --target_mse 0.1012
#PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb/model_supervised_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb/outputs_supervised_comparable_3/ --predictions_prefix 2nd_ep --target_mse 0.1023


# bbb - paper_proposal
## supervised
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_best_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_best_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_best_3/ --predictions_prefix 2nd_ep
## supervised whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done

## dino
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_dino_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_dino_best_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_dino_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_dino_best_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_dino_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_dino_best_3/ --predictions_prefix 2nd_ep
## dino whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_dino_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_dino_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done

## comparable
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_comparable_1/ --predictions_prefix 2nd_ep --target_mse 0.1129 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_comparable_2/ --predictions_prefix 2nd_ep --target_mse 0.1149 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_paper/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_paper/outputs_supervised_comparable_3/ --predictions_prefix 2nd_ep --target_mse 0.1122 --ensemble_size 1 ### custom value. otherwise duplicates

# bbb - graves
## supervised
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_best_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_best_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_best_3/ --predictions_prefix 2nd_ep
## supervised whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done

## dino
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_dino_best_1/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_dino_best_1/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_dino_best_2/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_dino_best_2/ --predictions_prefix 2nd_ep
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_dino_best_3/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_dino_best_3/ --predictions_prefix 2nd_ep
## dino whole training (dont stop at best epoch)
for i in $(seq 1 10); do PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_dino_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_dino_whole_training/$i/ --predictions_prefix 2nd_ep --ensemble_size 1 --target_mse -1 --filter_index_to_use $i; done

## comparable
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_comparable_1/ --predictions_prefix 2nd_ep --target_mse 0.1434 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_comparable_2/ --predictions_prefix 2nd_ep --target_mse 0.1497 --ensemble_size 1
PYTHONPATH=./ tsp python scripts/final_plots/ensembles.py --models_dir /home/markus/workspace/data/final_data/bbb_graves/model_supervised_20/ --dataset_dir /home/markus/datasets/drive360_prepared_4_5k/ --output_dir /home/markus/workspace/data/final_data/bbb_graves/outputs_supervised_comparable_3/ --predictions_prefix 2nd_ep --target_mse 0.1539 --ensemble_size 1


